# Generated by Django 4.2.2 on 2023-10-15 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appProduct', '0024_product_old_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Fiyat')),
                ('is_delete', models.BooleanField(default=False, verbose_name='')),
                ('created_date', models.DateTimeField(verbose_name='')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProduct.product', verbose_name='Ürün')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(verbose_name='Toplam Ücret')),
                ('status', models.CharField(choices=[('payment_waiting', 'Ödeme Bekliyor'), ('buyed', 'Ödeme Tamamlandı'), ('deleted', 'Silindi')], default='payment_waiting', max_length=20)),
                ('created_date', models.DateTimeField(verbose_name='oluşturma')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('items', models.ManyToManyField(blank=True, to='appCart.shoppingcartitem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Müşteri')),
            ],
        ),
    ]
