# Generated by Django 4.2.2 on 2023-10-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='total_price',
            field=models.FloatField(default=0, verbose_name='Toplam Ücret'),
        ),
        migrations.AlterField(
            model_name='shoppingcartitem',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma'),
        ),
        migrations.AlterField(
            model_name='shoppingcartitem',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Silindi'),
        ),
        migrations.AlterField(
            model_name='shoppingcartitem',
            name='price',
            field=models.FloatField(default=0, verbose_name='Fiyat'),
        ),
        migrations.AlterField(
            model_name='shoppingcartitem',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme'),
        ),
    ]
