# Generated by Django 4.2.2 on 2023-10-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCart', '0002_alter_shoppingcart_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='session_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
