# Generated by Django 4.2.2 on 2023-09-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Başlık ')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='carousel', verbose_name='Slayt Resmi ')),
                ('row', models.PositiveIntegerField(default=1, verbose_name='Sıra ')),
                ('status', models.CharField(choices=[('PSF', 'Pasif'), ('AKTF', 'Aktif')], default='PSF', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluştuma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sayfa Adı')),
                ('slug', models.SlugField(default='', max_length=200, verbose_name='Slug')),
                ('content', models.TextField(max_length=500000, verbose_name='İçerik')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='page', verbose_name='Resim')),
                ('status', models.CharField(choices=[('DRF', 'Taslak'), ('PSH', 'Yayınlandı'), ('DEL', 'Silindi')], default='DRF', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluştuma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
        ),
    ]
