# Generated by Django 4.2.2 on 2023-09-26 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': 'Slayt', 'verbose_name_plural': 'Slaytlar'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Sayfa', 'verbose_name_plural': 'Sayfalar'},
        ),
    ]
