# Generated by Django 4.2.2 on 2023-09-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPage', '0002_alter_carousel_options_alter_page_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='status',
            field=models.CharField(choices=[('PSF', 'Pasif'), ('AKTF', 'Aktif')], default='AKTF', max_length=10, verbose_name='Status'),
        ),
    ]
