# Generated by Django 4.2.2 on 2023-09-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPage', '0003_carousel_is_active_alter_carousel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Aktif | Pasif'),
        ),
    ]
