# Generated by Django 4.2.2 on 2023-09-28 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPage', '0004_alter_carousel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='is_active',
        ),
    ]
