# Generated by Django 4.2.2 on 2023-09-24 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Kategori Adı ')),
                ('slug', models.SlugField(default='')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='category', verbose_name='Kategori Resmi ')),
                ('status', models.CharField(choices=[('PSF', 'Pasif'), ('AKTF', 'Aktif')], default='PSF', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluştuma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Ürün Adı ')),
                ('slug', models.SlugField(default='')),
                ('content', models.TextField(max_length=500000, verbose_name='İçerik')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='category', verbose_name='Kategori Resmi ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Fiyat')),
                ('stock', models.PositiveSmallIntegerField(default=0, verbose_name='Stok')),
                ('status', models.CharField(choices=[('PSF', 'Pasif'), ('AKTF', 'Aktif')], default='PSF', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluştuma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('category', models.ForeignKey(default='-', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appProduct.category', verbose_name='Kategori')),
            ],
        ),
    ]
