# Generated by Django 4.2.2 on 2023-09-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProduct', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Alt Kategori', 'verbose_name_plural': 'Alt Kategoriler'},
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='sub_category',
            new_name='top_category',
        ),
        migrations.AddField(
            model_name='category',
            name='row_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Sıra '),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='row_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Sıra '),
        ),
    ]
