# Generated by Django 4.2.2 on 2023-09-27 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appProduct', '0008_alter_category_slug_alter_subcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('PSF', 'Pasif'), ('AKTF', 'Aktif')], default='AKTF', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('PSF', 'Pasif'), ('AKTF', 'Aktif')], default='AKTF', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='status',
            field=models.CharField(choices=[('PSF', 'Pasif'), ('AKTF', 'Aktif')], default='AKTF', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='top_category',
            field=models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, to='appProduct.category', verbose_name='Ana Kategori'),
        ),
    ]
