# Generated by Django 4.2.2 on 2023-09-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProduct', '0010_alter_subcategory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Aktif | Pasif'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Aktif | Pasif'),
        ),
    ]
