# Generated by Django 4.2.2 on 2023-10-03 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appProduct', '0011_alter_category_status_alter_subcategory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(limit_choices_to={'Category': models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appProduct.category', verbose_name='Kategori')}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appProduct.subcategory', verbose_name='Alt Kategori'),
        ),
    ]
