# Generated by Django 4.2.2 on 2023-10-03 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appProduct', '0014_alter_product_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urunler', to='appProduct.category', verbose_name='Kategori'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='top_category',
            field=models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, related_name='alt_kategoriler', to='appProduct.category', verbose_name='Ana Kategori'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ManyToManyField(related_name='urunler', to='appProduct.subcategory', verbose_name='Alt Kategori'),
        ),
    ]
