# Generated by Django 4.2.2 on 2023-10-03 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appProduct', '0015_alter_product_category_remove_product_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('top_category__row_number', 'row_number'), 'verbose_name': 'Alt Kategori', 'verbose_name_plural': 'Alt Kategoriler'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appProduct.category', verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='category', verbose_name='Ürün Resmi '),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ManyToManyField(to='appProduct.subcategory', verbose_name='Alt Kategori'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='top_category',
            field=models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, to='appProduct.category', verbose_name='Ana Kategori'),
        ),
    ]
