# Generated by Django 4.2.2 on 2023-10-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProduct', '0018_remove_product_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='appProduct.category', verbose_name='Kategori'),
        ),
    ]
