# Generated by Django 4.2.2 on 2023-10-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProduct', '0020_alter_product_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Ürün Resmi '),
        ),
    ]
