# Generated by Django 4.2.2 on 2023-10-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProduct', '0021_alter_product_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_home',
            field=models.BooleanField(default=False, verbose_name='Anasayfada'),
        ),
    ]
