# Generated by Django 4.2.2 on 2023-10-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProduct', '0022_product_is_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Yayınla'),
        ),
    ]
