# Generated by Django 4.2.2 on 2023-10-12 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProduct', '0023_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='EskiFiyat'),
        ),
    ]
